Ipek task sdep 5535
kwaiga8/better-cypress pull request #1
Opened 2023-12-11 13:33 UTC by ipekyilmaz35

test

2023-12-11 13:48 UTC, kwaiga8 requested changes
Please address the comments

2023-12-11 13:48 UTC, kwaiga8 commented on cypress/e2e/shopping/buyProducts.e2e.cy.ts
>    const loginPage: LoginPage = new LoginPage()
Please remove "--" from the end

2023-12-11 13:48 UTC, kwaiga8 commented on cypress/e2e/shopping/cartHandling.cy.ts
> +describe('User can add and remove items to the card in the shop inventory page', () => {
Change to: "User can add and remove items to the card"

2023-12-11 13:48 UTC, kwaiga8 commented on README.md
> +<p>Java + Selenium is the best option for automated UI tests? Let's try something lighter ; )
I would change to: "faster and lighter"

2023-12-13 10:12 UTC, ipekyilmaz35 commented
I have made the changes you mentioned for these files: readme, buyProducts, cartHandling

2023-12-13 13:06 UTC, ipekyilmaz35 commented
> Please address the comments

okay

2023-12-13 13:08 UTC, kwaiga8 approved these changes
Thats nice!

2023-12-13 13:09 UTC, merged